default_platform(:ios)

platform :ios do
  desc "Archive and upload to TestFlight (beta)"
  lane :beta do
    # Asume que el proyecto se encuentra en ios/App
    Dir.chdir("#{File.dirname(__FILE__)}/App") do
      cocoapods
      build_app(scheme: "App", export_method: "app-store")
      upload_to_testflight
    end
  end
end
